### ISSUE TITLE
UI/X wireframes for first release

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#112]
# Description

Design the UI/X for release.

# Tasks

- [ ] *Logo*
  - [ ] tabular icon?
  - [ ] "goodtables.io"
- [ ] *Brand/scheme*
- [ ] *Navigation*
  - [ ] Logo
  - [ ] Login/out
  - [ ] Dashboard (when logged in, the `/` route should show dashboard, when logged out, `/` shows landing page)
  - [ ] Settings
- [ ] *Landing View*
  - [ ] What is it
  - [ ] How you use it
  - [ ] You can pay for it (plans)
- [ ] *Dashboard View* (current http://goodtables.oklabs.org/dashboard)
  - [ ] A Feed where we see the latest **Job** of each source, and can click through to inspect that Job, or the Source
  - [ ] **Source**/**Job** object:
    - [ ] Name of source (“my data”, or "okfn/my-data")
    - [ ] Integration ("GitHub" or "AWS S3")
    - [ ] Link to Source Detail page
    - [ ] State of Source (which actually is the state of the latest **Job** for this **Source**) - (valid or invalid)
    - [ ] Link to the latest Job Detail Page
    - Datetime of the latest **Job**
    - Unique id of the latest **Job**
- [ ] *Source Detail View* (current http://goodtables.oklabs.org/github/repo/amercader/ne-data-test, this should be the job history)
  - [ ] Name of **Source** (“my data”, or "okfn/my-data")
  - [ ] Integration ("GitHub" or "AWS S3")
  - [ ] Datetime of adding this **Source** to goodtables
  - [ ] # of **Jobs** done for this **Source** in goodtables
  - [ ] Current state of **Source** (which actually is the state of the latest **Job** for this **Source**) 
  - [ ] Current **Report** of **Source** (which actually is the **Report** of the latest **Job** for this **Source**)
  - [ ] Latest **Job** Detail
    - [ ] State
    - [ ] Datetime
    - [ ] Unique id
    - [ ] Link to the job detail page
  - [ ] List of job history
    - [ ] Per job history object:
      - [ ] State
      - [ ] Datetime
      - [ ] Unique id
      - [ ] Link to the job detail
- [ ] *Job Detail View* (current http://goodtables.oklabs.org/jobs/badfb950-86ea-4068-bac4-5c13ecc9337c)
  - [ ] **Source** name
  - [ ] Link back to **Source** Detail View
  - [ ] State
  - [ ] Datetime
  - [ ] Unique id
  - [ ] **Report**
- [ ] *Settings View*
  - [ ] Profile Section (Read Only)
    - [ ] Name
    - [ ] Email
    - [ ] Avatar
  - [ ] Plan Section
    - [ ] Show Plans with current one active
    - [ ] Action to change plans
  - [ ] Integrations Section
    - [ ] GitHub Integration
      - [ ] IF NOT integrated
        - [ ] Integration specific steps to make the integration
      - [ ] IF Integrated
        - [ ] List Sources
          - [ ] Action to Remove a Source
        - [ ] Add a Source
          - [ ] Integration specific steps to add a source
    - [ ] AWS S3 Integration
      - [ ] IF NOT integrated
        - [ ] Integration specific steps to make the integration
      - [ ] IF Integrated
        - [ ] List Sources
          - [ ] Action to Remove a Source
        - [ ] Add a Source
          - [ ] Integration specific steps to add a source

Some examples:

https://travis-ci.org/ckan/ckanext-dcat
https://travis-ci.org/ckan/ckanext-dcat/builds

https://circleci.com/gh/ckan/ckan

**Comment by pwalsh** [comment]
@amercader please review for emissions etc.

@smth please review for questions in prep to work on this.

@jobarratt please review as well

**Comment by jobarratt** [comment]
The question for me is how this works in terms of the paid service. @pwalsh and i need to discuss this because at the moment i’m not clear and have some questions/ideas. 

@smth  i think you have complete freedom when it comes to the branding. I think it is more important that it has its own strong identity rather than conform to any OKI/Frictionless Data brand. There will be other Frictionless Data ‘products’ such as the Registry, DQD and we could make a decision make them a group of products with a join identity - but this is your decision and i think there is no requirement for this. 

In the long term we need to think about how this would might be included as part of a services.okfn.org / frictionlessdata.io website which features all of our paid-for products. So we should keep this in mind but i do not think that this should block things here.

**Comment by amercader** [comment]
@jobarratt I think that will become clear eventually as we flesh out #113 and #114 but my sense is that paid plans will allow access to more than X sources/files/GB and/or private sources. We could also consider offer in-premise installation support.

**Comment by amercader** [comment]
@smth We'll need some rough estimates for this. Do you want to split it in different issues per eg logo / layout / each page? Whatever it works better for you.

**Comment by smth** [comment]
Not having access to the working prototype, I'm basing this dashboard layout on the list above:

![dashboard_wireframe_01](https://cloud.githubusercontent.com/assets/1375708/22936935/df23092c-f2ce-11e6-8a75-866369d892cb.png)

This begs the question:
Do we have a sense of how many sources a user is likely to have? Is showing this many (on a medium sized screen) useful?
If we think it will vary dramatically, maybe we should consider multiple layouts, perhaps determined by the number of sources.

**Comment by smth** [comment]
In terms of logo / brand, this is where I'm at:
<img width="960" alt="brand_01" src="https://cloud.githubusercontent.com/assets/1375708/22940698/ca18bc6e-f2da-11e6-9eba-1fe2f9324617.png">

**Comment by jobarrattt** [comment]
Love how this is looking @smth

**Comment by amercader** [comment]
I really like the image / brand @smth! particularly the tilted logo. Would that work on the header as well?

In terms of the dashboard, remember that users should probably only see the *last job* for each source (gh repo or s3 bucket), and we can limit to only the 5 / 10 / whatever more recently updated ones. Definitely not as many as in your case :) Another option is to show the status of the last x jobs per source and not just the last one (like in here but with sources instead of branches https://travis-ci.org/frictionlessdata/goodtables.io/branches)

I think it's reasonable to expect most users to have 1 to 10 sources, with some power users more than that.

One thing that should be prominent is the buttons / links to add new sources, specially on a first visit (Add Repository and Add Bucket buttons on the current site):

![zvw4w3g](https://cloud.githubusercontent.com/assets/200230/22972202/91f88dc8-f370-11e6-85cb-a0c8475fc506.png)

Sorry about not having a live site, we'll try to get something up asap

**Comment by smth** [comment]
Sorry, that wireframe was pretty unclear. Each box was intended to be a different source, so you are only seeing one job per source (and there are 30+ sources).

If we are saying maximum of ten sources, plus two button, then it might make sense to include multiple jobs, on larger screens at least.

Another option (as we've probably got space) might be to show the latest source or job detail view, in the dashboard view?

**Comment by amercader** [comment]
> If we are saying maximum of ten sources, plus two button

The idea is to add support for more source types in the future (eg Google Drive, Dropbox, etc)

I quite like the idea of showing the status of the last 5 jobs per source to get an overview (I'm going to probably regret this when I need to write the DB queries) and we can show source and job details as you said.

It's worth noting that the dashboard it's important because it's what the users will first see but once you've configured your sources I don't think people will visit it often. Most people will arrive to the job report page linked from Github or a notification.

**Comment by roll** [comment]
@smth 
@amercader 
I suppose we should take into account that this problem has been already solved pretty successfully earlier by services like https://travis-ci.org/, https://circleci.com etc So I think we could get an inspiration from services like this about UX because they solve exactly the same problem.

In some aspects they different by I think we could learn a lot from there UX. For example I work with Travis on every day basis and that's a good example of `don't make me think` experience - just seamlessly getting all I need for work.

**Comment by amercader** [comment]
I agree, in terms of user flow and experience I would definitely look into travis or circleci

**Comment by smth** [comment]
So rather than drawing wireframes based on Travis, shall we use Travis as the wireframe?

I've been trying to visualise what this does, for the landing page:
![gtio_home_01](https://cloud.githubusercontent.com/assets/1375708/23134524/06989568-f78d-11e6-8f52-1f031ea83deb.jpg)

**Comment by smth** [comment]
After some more thought I decided there are enough differences to warrant wireframes. I started working on one for the source page, based on the Travis layout: 

![source_wireframe_01](https://cloud.githubusercontent.com/assets/1375708/23158692/051e5fb6-f818-11e6-90e9-2a8c4def60a4.png)

It occurred to me that we may not need as much space for our reports. The [screenshots](https://imgur.com/a/sbN2H) that I have suggest that we don't, but I'm guessing that reports could be longer. Can anyone clarify? If there is more info to go in there, could I have some examples please.

**Comment by smth** [comment]
And a dashboard that includes latest job:
![dashboard_wireframe_02](https://cloud.githubusercontent.com/assets/1375708/23160941/34cfb572-f820-11e6-9779-f9fd9d450c4b.png)

**Comment by smth** [comment]
As for he landing page, if we have any copy on:

- What is it
- How you use it
- (how) You can pay for it 
- plans

that'd be useful.

**Comment by amercader** [comment]
@jobarratt can you work on the copy?

**Comment by smth** [comment]
I have added a couple of missing items from the dashboard. Was also thinking that in this view, maybe a job with a failed test should be highlighted (because it presumably requires attention). This is feeling much more like a dashboard to me now:

![dashboard_wireframe_03](https://cloud.githubusercontent.com/assets/1375708/23212401/7bede83c-f8fe-11e6-8819-dafa178edf39.png)

The dashboard described in the original post could essentially become an 'all sources' view:

![sources_wireframe_01](https://cloud.githubusercontent.com/assets/1375708/23212433/a70ce09a-f8fe-11e6-8583-c8ac1d1e4971.png)

If we have this page, it seems like it might be a more logical place to do the adding and removal of sources (rather than a settings page).

This would leave just the enabling and disabling of integrations on the settings page (maybe even this could be done from the sources page). I'm not really sure what this process entails at the moment though.

![settings_wireframe_01](https://cloud.githubusercontent.com/assets/1375708/23212577/47b91d42-f8ff-11e6-9be4-af4c52b5a1e3.png)

(Need more info on the plans before I can wireframe that section in more detail)

**Comment by jobarrattt** [comment]
@amercader yep i will do this tomorrow

**Comment by smth** [comment]
This is what I'm anticipating the landing page content to look like:

![landing_wireframe_01](https://cloud.githubusercontent.com/assets/1375708/23216684/bd8eddcc-f90e-11e6-8dd4-a7f6676d83e6.png)

Styling:

![gtio_home_01](https://cloud.githubusercontent.com/assets/1375708/23216699/d34fee4e-f90e-11e6-8241-b12a563fbb16.jpg)

**Comment by amercader** [comment]
@samsmith this is looking more and more exciting :clap: . I'll provide more feedback tomorrow

@jobarratt testing testing

**Comment by amercader** [comment]
@smth here are some thoughts (I just realized I've been pinging the wrong sam for a while :p )

> maybe a job with a failed test should be highlighted (because it presumably requires attention)

Does this mean that when loading the dashboard the main details on the right will be of the last failed job (not the most recent one)?  I'm not sure if that's what I would expect, but I'm not a  big fan of showing the last job ever like Travis does (https://travis-ci.org), so let's give it a go. Perhaps we can add a "Last failing job" heading somewhere to make this clear. The other option as we discussed before is having just a list of sources with the last status (like CircleCI https://circleci.com/dashboard), but let's stick with what you think and iterate on it.


> The dashboard described in the original post could essentially become an 'all sources' view:
> If we have this page, it seems like it might be a more logical place to do the adding and removal of sources 

I'd really like to have the option to add sources on the dashboard and not having to navigate to some other page, perhaps as a plus sign next to the tabs?

Some more context on enabling/disabling integrations and adding sources. It really depends on the source type. 

For Github "activating the integration" means authorizing the app via OAuth. Right now this is done in one step when you log in with GitHub (basically we ask for all perms just to log in), but eventually this will be split into a separate oauth call (https://github.com/frictionlessdata/goodtables.io/issues/124). So the process will be:

1. Log in
2. Go to a settings page
3. Click on "Authorize GitHub" and accept the perms
4. Synchronize account to get the big list of repos (what's in http://staging.goodtables.io/github/settings)
5. Flip the switch on the repo(s) you want to validate

I think this needs a dedicated page on its own. This is where people will remove the integration with a particular repo as well. I guess you can Inactivate the intgration by removing all perms given and disabling all repos (if necessary, other users might have also set it up) 

For S3 the process is really different as the authorization model is also really different, basically:

1. Log in 
2. Go to a settings page
3. Submit form with bucket name, access key and secret

If all goes well the bucket gets added and that's it. There is a list of your buckets with a link to remove the integration for each of them. There is no global Activating / Disabling integration per se.

I guess my point is that we need a dedicated page for each source type, whether if that's in Settings or Add source I don't know

> (Need more info on the plans before I can wireframe that section in more detail)

There's not much info on the plans as far as I'm aware but I think we'll start with just 2, free and paid (cc @pwalsh)

Landing Page looks great

**Comment by jobarratt** [comment]
@smth I agree this is looking great! Hoping to speak to @pwalsh this week but i know i need to get this to you.

**Comment by jobarratt** [comment]
@smth @amercader you mentioned you had done the copy for this. Do you have all you need for now, and i can i review it somewhere?

p.s. i think i am getting notified now. A strange thing going on and a not strange thing but i think i've cracked it.

**Comment by amercader** [comment]
> @amercader you mentioned you had done the copy for this

@jobarratt I haven't done any copy

**Comment by jobarratt** [comment]
@amercader i missunderstood a conversation on the new standup then. I'm on this now.

**Comment by pwalsh** [comment]
two levels: free (default plan) and paid

**Comment by smth** [comment]
@amercader 

> Does this mean that when loading the dashboard the main details on the right will be of the last failed job (not the most recent one)?

That's what I meant, but just an idea.

> I'd really like to have the option to add sources on the dashboard and not having to navigate to some other page, perhaps as a plus sign next to the tabs?

That is there, above the list of sources.

@pwalsh so we don't have details about the differences between the plans yet?

**Comment by pwalsh** [comment]
Yes we do, here https://github.com/frictionlessdata/goodtables.io/issues/113 but admittedly it is rather cryptic for non-programmers, sorry about that.

Free:

- public repos
- up to max number of files in repo
- one job at a time

Paid:

- private repos
- unlimited (effectively) file limit
- multiple jobs can run at once (say, 5 or a similar number)

Also I think S3 support will be on the paid plan at first, but need to decide.

**Comment by smth** [comment]
Dashboard mock-up is about at the stage of the wireframe https://smth.github.io/goodtables-ui/dashboard/

**Comment by amercader** [comment]
Closing in favour of individual pages issues
