### ISSUE TITLE
Implement access controls to support restricting usage

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#113]
# Description

We need to implement access controls to support restricting usage. This allows us to hook in to control resource constraints, and to unlock some of those constraints for paid usage of the service.

## User story

As a Product Owner, I want to be able to limit access to platform features and frequency of usage, so that I can control resource constraints, and offer paid plans for particular usage patterns.

# Tasks

- [ ] Implement a system for access control/restrictions. This will be checked before running a job, returning some type of Boolean on whether a job can be accepted or not, and if not, provide data to give feedback to end users as to why.
- [ ] Allow configuration of restrictions per **Source**
  - [ ] Is public?
  - [ ] Exceeds file limit (default 100)? (assumes a global that says what limit is - "your source has 10,000 files. Sources with more than 100 files need a paid plan.")
- [ ] Allow configuration of restrictions per *User*
  - [ ] Concurrent *Job* limit (default 1)? (assumes a global that says what limit is - "On the free plan, the concurrent job limit is 1. Upgrade for unrestricted job concurrency.")

**Comment by pwalsh** [comment]
@amercader assigned for you to check if I need to clarify more, and if not, to do initial high-level estimate.

**Comment by pwalsh** [comment]
@amercader why are estimates pending on this one?

**Comment by amercader** [comment]
@pwalsh I just wanted to have a better think about it and it slipped my mind. I added now 5 days just because the concurrency handling is likely to take a lot of investigation and trialling.

As with many other features in the project it gets complicated due to the different nature of the sources (GitHub vs S3 vs ...). In general I don't think file limit it's the most important check we should do. We can (and we definitely should have an internal limit) but we need to combine it with other checks. The most useful from my point of view are:

* Concurrent jobs: 1 on free plan, 2 or more on paid plan ("Upgrade for unrestricted job concurrency" is not realistic) We really need to investigate how to handle and scale this on our current deployment. To implement it we need to perform a check *before each job*, and queue the job if necessary to wait until the other one is finished.

* Public / private sources: On GitHub: only public repos on free plan, support for private repos on paid plan. On S3 this doesn't make sense because all buckets are private by default so I'd put a limit on the number of buckets on the free plan. To implement it we need to perform a check *before adding a source*

**Comment by amercader** [comment]
Glad we reached pretty much the same conclusions https://github.com/frictionlessdata/goodtables.io/issues/112#issuecomment-282979977

**Comment by pwalsh** [comment]
@amercader when we put a job on the queue for processing, is there a record somewhere that says "job received, status pending"? Or, is all the logic in the job on the queue itself. If the former, I guess the concurrency check is relatively straightforward (ignoring any corner cases, just basic first iteration on implementing it).

**Comment by amercader** [comment]
@pwalsh Yes, we are storing this in the DB. The check itself is not what worries me but what to do if it fails (eg how to hold an incoming job or jobs, how to point it to relevant worker, etc). All this is probably builtin in Celery, we just need to investigate a bit.

**Comment by pwalsh** [comment]
that is fine - we are doing this just to support the service and get it up. we'll launch with what is easy, open issues for the problems, and iterate on it in another stage.

**Comment by roll** [comment]
@pwalsh 
@amercader 
I haven't found out-of-box solution for our situation in celery so it seems we should manage those rate limits by ourselves. 

It should be pretty straight-forward like this:
- instead of running jobs integrations/api should write to `jobs` table with status like planned with `validation_conf` and `job_conf`(optional but goof to track and show as job config to the user)
- we need regular `scheduler` celery task which will be:
  - start/ignore jobs based on all our business rules (per user limit, account type etc)
  - handle staled jobs, updating errors etc - all maintenance on jobs

Also it will improve our design because all jobs (celery calls) will be running from one place - more modular and easy-to-test design.

**Comment by amercader** [comment]
Sounds like a good approach @roll.

**Comment by amercader** [comment]
Some more thoughts on this, would appreciate your thoughts @pwalsh @roll 

One thing I've been thinking about is that jobs must be somehow linked to at least a particular user to be able to apply limits that are based on plans. Webhook endpoints don't have authentication so we need to use the existing model to do that.

The most obvious way is `job.source.users`, but that means that we need a way to decide which user to pick to check the plan permissions.

Let's say that a new job is created on the Github source `myorg/myrepo` (which is a private repo).
There are 4 users linked to this source (because when they synced their accounts that was one of the GH repos that they had access to):

* `user1` -  Free plan
* `user2` -  Paid Plan 2 ($$$)
* `user3` -  Paid Plan 1 ($)
* `user4` -  Free plan

For this particular job, the limits that would apply would be the ones from Paid Plan 2 as it's the highest plan among all users linked to this source.

This will cover creating jobs on private sources, number of concurrent jobs per source and number of files per source.

In terms of accessing reports from private sources (private GH buckets or all S3 buckets) to keep it simple for Beta we could limit it to the logged in user being part of a paid plan (and having access to the source of course). That will mean that if eg even if all 4 previous users belong to `myorg` and could access `myrepo` on Github only `user2` and `user3` could see the reports.

This seems to me like the minimum approach that we can implement for a first version given the requirements, but happy to hear other thoughts.

Going forward we want all of them to be able to see the reports of course. To do that we can:

1. Add the concept of collaborators. Users with a paid plan can add other GTIO users to their plan, allowing them the same plan features (namely access to private repos). This would be required for S3 and probably for other future integrations. We could also have a global switch per source that allows access to the reports to all users as a first step.

2. Replicate Github auth model internally. When people sync their accounts store the access information for each repo and decide based on that if a user can see the reports for a repo or not.

Given that 1 needs to be implemented anyway I'm inclined to go for that one. This seems to be the approach used by Travis when they mention "Unlimited collaborators" on their plan page.

**Comment by pwalsh** [comment]
Just summarising ( I think it is in line with your last message too @amercader ):

- paid plans belong to users
- paid plan levels are applied to all jobs that the user owns/admins
- *some* sources have a collaborative model (GitHub): collaborators "acquire" to rights on jobs for that source based on the rights of the owner/admins of that resource - same as how travis, coveralls, circleci and GitHub itself works
- we only have one paid plan so optimising for multiple paid plans at this stage is not needed

For your point (1) - adding the concept of collaborators: I don't see why we want to add this to our own business logic, when we can get the collaboration graph dynamically from sources that allow collaboration (GH), but maybe I am missing something. 

I understand that a use case will likely emerge in the future for, say, collaborators on a S3 bucket, and your suggestion would accomodate this future possibility, but it is well beyond scope right now (good thing to document in the backlog).

**Comment by amercader** [comment]
> For your point (1) - adding the concept of collaborators: I don't see why we want to add this to our own business logic, when we can get the collaboration graph dynamically from sources that allow collaboration (GH), but maybe I am missing something.

I was just thinking about S3 buckets, but if we stick to everyone just being allowed to see their own buckets reports that will work for now.

**Comment by pwalsh** [comment]
@amercader gr8
