### ISSUE TITLE
Plan entity to represent user plans

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#114]
# Description

Users need a **Plan**. A plan is a user-facing concept that indicates access and restrictions, and also internally hooks into a system for access and restrictions. Plans hold information on: 

- plan name,
- plan description
- plan value (in $).
- plan frequency (enum: month or year) - default to month
- timestamps (created_on + last_modified)
- plan identifier (a string that associated this plan object with a plan object on the payment backend)

(eventually plans will have sets of rules - needed when multiple plans exist. do not consider this now - noting here as it as been purposely omitted)

*Closely related to https://github.com/frictionlessdata/goodtables.io/issues/113 but not strictly dependent not a dependency.*

# Tasks

- [ ] Create a `plan` model and table, and populate it with 2 records
  - [ ] All users have a plan. By default, users get a default plan, named "Free".
  - [ ] A second plan called "Paid", monthly, $10 just for purpose of adding something now.
-  [ ] Link plans to users (ie `User.plan`)

**Comment by pwalsh** [comment]
@amercader assigned for questions and then high-level estimate

**Comment by amercader** [comment]
See #173
