### ISSUE TITLE
Server setup

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#119]
# Description

Final setup of the service for production usage.

# Tasks

- [x] Setup production environment
- [x] Setup staging environment
- [x] map names to production and staging environments
- [x] Setup Sentry for exception logging
- [x] Setup paper trail for general logging
- [ ] Setup database backups to S3
- [ ] **Force** ssl

**Comment by pwalsh** [comment]
@amercader @akariv will help us here to get everything in place.

**Comment by amercader** [comment]
@pwalsh @akariv please adjust the estimate if necessary

**Comment by roll** [comment]
@akariv 
So we're only miss here `Setup database backups to S3`? (force ssl is part of #135?)

**Comment by amercader** [comment]
@akariv  I tried to enable the `dockercloud-db-to-s3` image on our stack but there is a mismatch with the pg versions and it didn't work, so I've stopped it for now:

```
pg_dump: server version: 9.6.1; pg_dump version: 9.5.6
pg_dump: aborting because of server version mismatch
```

**Comment by akariv** [comment]
Been fixed for a few days now, closing.
