### ISSUE TITLE
Extract Report external reusable component

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#150]
_Moving it here to simplify understanding of what we'are trying to achieve._ (text from @pwalsh)

# Description

We have good tables reports in several templates in different codebase. It will be nice to centralise the templates and provide them as part of the library.

## Dependent services

- [OS Packager](https://github.com/openspending/os-packager)
- [GoodTables Web](https://github.com/frictionlessdata/goodtables-web)
- [DataPackagist](https://github.com/frictionlessdata/datapackagist)

# Tasks

- [ ] `contrib` or `bindings` module to import + render templates
  - [ ] Angular 1 first so we can ship for OS, and others can be based on the pattern
  - We have an example of similar template binding approach in [babbage.ui](https://github.com/openspending/babbage.ui/tree/master/src/bindings)

---

Also https://github.com/openspending/openspending/issues/1180

---

Now we have 3 experimental components:
- https://github.com/frictionlessdata/goodtables-vue-js
- https://github.com/frictionlessdata/goodtables-react-js
- https://github.com/frictionlessdata/goodtables-angular-js

Next steps TBD after #112 

---

- [x] Goodtables report rendering library should work via npm
- [x] Report view should support dataset errors

**Comment by pwalsh** [comment]
@roll @amercader which milestone should this belong to? The issue has jumped around across different repos, the scope has changed from my original goals, so, I need some help understanding fully what decisions where made, why they were made, and what it means for each of:

- goodtables.io beta
- goodtables-js (which other apps depend on)

**Comment by roll** [comment]
@pwalsh 
@amercader 
I've put everything related to this task here to stop fragmentaion of tracking. I'll be able to write more detailed current status and plan of finishing it (shipping format for GTIO and othet clients) today.

**Comment by amercader** [comment]
This is one if not the most critical part of the frontend so I'd say that we definitely need it for Beta (meaning a working UI for the report). I'll wait for your report to clarify @roll

**Comment by roll** [comment]
# A short story of ~~time~~ this issue

- there was initial requirements to write goodtables report render function using angular1 (and then other) templates - https://github.com/frictionlessdata/goodtables-js/issues/16
- we've decided to use vue.js for GTIO and modern frontend frameworks for other OKI projects
- after learning recommended nowa-days way of shipping UI component I've extracted report rendering work into:
  - https://github.com/frictionlessdata/goodtables-vue-js
  - https://github.com/frictionlessdata/goodtables-react-js (experimental repo I've written in my personal time)
  - https://github.com/frictionlessdata/goodtables-angular-js (experimental repo I've written in my personal time)
- I've misundersdtood that for new GTIO project and other clients we're going to use exactly the same old goodtables-web design for report rendeting so I've implemeted different prototype going to wait for #112

# Current thoughts about component shipping

After I've implemented all this components using different frameworks I've started to doubt our approach of having written it for every framework we need:
- GTIO uses vue.js, OS uses Angular1, DPRegistry uses React, also there are other possible clients
- modern component it's no only about templates, it's action controllers, local state, unit tests etc
- so maintaining and updating 2-4 different implementation of the same thing could be painful and error-prone

So I've figure out that based on vue.js extremaly small size we could ship universal component without external dependencies with API like this:
```html

<div id="report"></div>

<-- This will be around 20kb(!!!) gziped with vue.js inside -->
<script src="//unpkg.com/goodtables-report/dist/goodtables-report.js"></script>
<script>
goodtablesReport.render(document.getElementById('app'), <YOUR_GOODTABLES_REPORT>)
</script>

```

It will allow us:
- to maintain only one high-quality component (simplify improvements etc) 
- don't write any other code to OS integration for example (could be used from today)
- allow all other partners to start their integrations without any delay 

# What we're missing on this iteration visual design-wise

So if we really need exactly the same as `goodtables-web design`:

- support for dataset level errors (there are could be errors not related to any files)
- support for multiple files - new goodtables report contains multiple files when design supports only one file
- I suppose sync with #112 for general styling - colors etc
- I need to update written component after it (it's not time consuming - 0.5d-1d)

# How future goodtables report could look like

I've create an issue for backlog with ideas of report view improvements based on my prototypes and experience of goodtables-web usage.

@akariv 
@amercader 
@pwalsh 
@smth

**Comment by pwalsh** [comment]
@roll have have a few questions, but at a fundamental level, wouldn't any implementation need to wrap what you include in some type of component native to the framework anyway, in order to manage data and state in general? Assuming yes, one would end up rewriting the boilerplate you are trying to avoid anyway.

**Comment by pwalsh** [comment]
@roll also I don't exactly understand why you do not consider the approach we took in OS good enough. An appeal to best practices is not enough here: rather, I'd like to understand how, exactly, it is not a manageable way to do this.

**Comment by roll** [comment]
Extracted to https://github.com/frictionlessdata/goodtables-ui
