### ISSUE TITLE
Finish Report component implementation

### ISSUE THREAD

**Issue by amercader** [frictionlessdata/goodtables.io#179]
# Overview

The report component should be improved.

# Tasks

- [ ] Valid files background color

    ![akksli5](https://cloud.githubusercontent.com/assets/200230/24910568/0d9a1850-1ec0-11e7-9bb3-280ce04cd1f9.png)

- [ ] Only display a preview of 10 rows per error group (+ a "Only 10 rows with errors are displayed" message if necessary)
- [ ] Add horizontal scrolling to error groups

    ![i8xewds](https://cloud.githubusercontent.com/assets/200230/24362933/35fcbb2e-1306-11e7-898c-2ef595ba122e.png)

- [ ] Close popups on next click (`data-trigger="focus"`)

**Comment by roll** [comment]
MERGED to #182
for easier tracking
