### ISSUE TITLE
Finish Header component implementation

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#183]
# Overview

In our design draft we don't have any header - https://smth.github.io/goodtables-ui/dashboard/. But we really need one to have `Login` button, user name etc. So we just added default bootstrap header http://staging.goodtables.io/dashboard which looks awful.

# Tasks

- [ ] create proper design
- [ ] implement it in `Header` component
- [ ] remove link to user page - we don't have one for now

**Comment by roll** [comment]
MERGED
#187
