### ISSUE TITLE
Merge github sources after repo renaming

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#234]
# Overview

For now after renaming there will be 2 sources - we should merge it based on `github_id`.

# TODO

- [x] check existent repos for uniqueness
- [x] `sync_github_repos` should take it into account
- [x] we should have unique constraint on `sources.conf->github_id`

**Comment by Tweety79rw** [comment]
I can confirm this is working.

**Comment by roll** [comment]
@Tweety79rw 
Thanks!
