### ISSUE TITLE
Demo view examples and minor fixes

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#256]
# Overview

Provide an example file and schema as http links. For simplicity, put these links as the form field placeholders. If the user has not pasted her own links, or uploaded her own files, then, use these placeholders.

# Tasks

- [x] add examples
- [x] fix links on the page
- [x] fix staging subdomain - MOVED #259
- [ ] report on trello
