### ISSUE TITLE
Validation job and jobs runner [3d]

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#3]
# Description

The GoodTables.io job runner takes a payload passed to it from some public-facing API, and runs goodtables against this payload. The payload is a configuration object which contains primarily the paths to the files to validate and schemas to use. Actually, the job runner manages many many of these jobs in a queue. 

All the scheduling logic should simply be part of the framework we use - Celery in this case. 

# Tasks

- [x] Define the parameters needed for the validation job to run (required by #6)
- [x] Set up Celery: requirements, configuration, default queues, etc
- [x] Write the goodtables based function that runs the validation and outputs a JSON report, and set it up as Celery task

# Estimates

2
