### ISSUE TITLE
Improve job view

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#30]
# Overview

For now it just reflects `goodtables` report structure:

![localhost 5000 job 78be4c2c 3dad 4816 937a 2a2d1feb61ff](https://cloud.githubusercontent.com/assets/557395/20389095/ed454f9c-acd8-11e6-9c12-484c29b41ca7.png)

# Tasks

- [ ] merge `overview` and `dataset` tables/job/6bee23f1-0efa-4ad4-8fa5-5d878b30a322
- [ ] instead of `table-1` etc show source url - requires https://github.com/frictionlessdata/goodtables-py/issues/122
- [ ] sync with @pwalsh @danfowler @jobarratt what's needed for MVP to show in pilots
