### ISSUE TITLE
Clean the codebase

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#48]
# Overview

After MVP we need to clean our codebase a little bit removing not used parts etc

# Tasks

- [ ] remove examples
- [ ] remove commands?
- [ ] remove tox.ini?
- [ ] remove setup.cfg(py?=)?
- [ ] remove `result_backend` if it's not needed by chains - http://docs.celeryproject.org/en/latest/userguide/canvas.html
- [ ] updated readme

**Comment by pwalsh** [comment]
For now, putting this in beta, not alpha. It is too early to have a dedicated refactoring tasks IMHO. Of course, some of these could get picked up while doing other tasks.

**Comment by roll** [comment]
@pwalsh 
All of them are pretty minor. Renaming, deleting unused things, moving functions etc. No coding here. Like a few hours of work for the whole task. 

Still recommend to do it as soon as possible (when @amercader will be having time for it) because some messy parts of codebase are slowing down the development.

**Comment by pwalsh** [comment]
@amercader I'm not to fussed about this for Beta, but I assume you and @roll just fix what comes up as you touch parts, so leaving it here of course with assignment to each of you.

**Comment by roll** [comment]
@amercader 
We could finish it straight after the Beta release. There are many minor things.
