### ISSUE TITLE
GitHub integration

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#5]
# Description

A continuous (data) validation process has an important feature - it needs to be *automated*. We want to use various hooks/APIs on 3rd party services to say "hey, here are some new files, please run the data validation again".

Additionally, some services (notably GitHub), include APIs that allow external services to add small pieces of information to the native UI. This is good! We'd really like to show a little "data is valid" message on PRs, for example, just like Travis shows for test runners.

# Tasks

- [ ] Investigate what type of GitHub [integration](https://developer.github.com/early-access/integrations/integrations-vs-oauth-applications/) we need to 
- [x] For a first prototype we could just install a webhook manually in one or more repos
- [x] Provide an endpoint that listens to GitHub webhooks, clones the repo calculates the affected files and creates the validation job
- [x] Integrate with the GitHub [Status API](https://developer.github.com/v3/repos/statuses/) to reflect the outcome of the job on GitHub's UI for PRs, commits, etc

Nice to have:

- [ ] Integrate with GitHub to the auth API so people can choose what repositories to activate (focus on public ones first)

# Estimate

3

**Comment by amercader** [comment]
Some stuff working on #15, still to do generally:

- [ ] Make the repo cloning async, connect with validation queue
- [ ] Authenticate user via Github

The latter is required for

- [ ] Use Status API to reflect status on Github UI
- [ ] Validate payload origin based on secret
- [ ] Automatically create webhook on repo (part of Integrations)

**Comment by roll** [comment]
@amercader 
No chances to use Tree API for MVP?

**Comment by amercader** [comment]
@roll I'm worried about using cloning as well in terms of scaling. For the MVP I think it's fine to stick with cloning though. This can be improved later as the input (what we get from the push webhook payload) and output (list of paths for the validation task) won't change.

In theory we could do one of the following:

1. Use the [Tree API](https://developer.github.com/v3/git/trees/#get-a-tree-recursively) to get all paths in the repo + Match against goodtables.yml + Get the files using the [contents API](https://developer.github.com/v3/repos/contents/#get-contents)
2. Get the files changed or added from the push webhook payload + Match against goodtables.yml + Get the files using the [contents API](https://developer.github.com/v3/repos/contents/#get-contents)
3. Downlod a [compressed archive](https://developer.github.com/v3/repos/contents/#get-archive-link) + extract + Match against goodtables.yml

I'm not sure what's the most efficient one, or whether the simplicity of the cloning one is worth the scaling worries. We'll have to investigate a bit more.

**Comment by pwalsh** [comment]
@amercader this issue has become overloaded. I'm going to close and break out different issues.

**Comment by amercader** [comment]
All the remaining tasks in here have they own issue now
