### ISSUE TITLE
Implement goodtables badges

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#55]
# Description

The UI needs to have badges integration and instructions for the user.

Options for endpoint:

1. Have an endpoint that checks status and redirects to the relevant status image from shields.io
2. Have an endpoint that checks status and outputs a svg
3. Submit a PR to shields.io so `https://img.shields.io/goodtablesio/<integration>/<source>.svg` queries a GTIO endpoint and returns an svg directly.

Looking at the PRs on shields.io it doesn't look like it would happen soon so I'll move 3 to another issue for the future. If we center on just data: valid/invalid for now I think I'll go for 2, with some static svg that we serve depending on the result of the last job check

# Tasks

- [x] Add 2 SVGs (or 4 if we want to support more styles) to somewhere that can be served statically
- [x] Add helper that checks status of last job for a source
- [x] Add badge endpoint that sanitizes source description (name), calls the previous helper and uses `send_file` to return the relevant SVG.
- [ ] Add small snippet in the source page that generates the embed code for the badge

URL could be `/badge/{integration-name}/{source-name}.svg[?style=flat|flat-squared]`. eg:

goodtables.io/badge/github/frictionlessdata/example-gtio.svg
goodtables.io/badge/s3/some-s3-bucket.svg
goodtables.io/badge/dropbox/{source-id}.svg

**Comment by amercader** [comment]
Implemented in #162. This can be optimized as described in #161. Issue for the frontend widget is #163
