### ISSUE TITLE
S3 integration

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#58]
# Description

As a user, I want to run good tables against a directory in S3, so I can validate data using my existing S3-based workflows.

## Notes

We can leverage AWS Lambda to get push notifications of new files hitting the "filesystem". This would mean that integration is about configuring S3, a lambda function, and a notification queue. Alternatively, we'd need a pull-based job runner that checks for files, possibly checks their hashes against previously known to see if there are changes, and then runs.

# Tasks

- [ ] TBD

**Comment by pwalsh** [comment]
Also see https://github.com/frictionlessdata/goodtables.io/issues/59

**Comment by pwalsh** [comment]
@amercader note that we have an internal use case for this before we even use it with a pilot partner - we could run it against the OpenSpending Datastore ( cc @akariv ).

**Comment by pwalsh** [comment]
This should cover all API and UI, so will need to be broken down when started.

**Comment by amercader** [comment]
OK, here's what I've found so far.

I wasted a lot of time investigating if Amazon's [OAuth login support](http://login.amazon.com/) would give us an access token to have a workflow similar to the GitHub one. Sadly that doesn't give you an access code that can be used for interacting with AWS APIs (via boto). There doesn't seem to be any alternative to the users providing an Access key and a Secret key.

This doesn't sound too good, and people would need to create a new IAM user with a custom policy that granted access only to the relevant bucket(s) (and ideally a group, and assign the user to that group). We will need to guide users through that process, and probably provide a template of the policy document filled with the bucket names. It looks something like this:

```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::test"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject"
            ],
            "Resource": [
                "arn:aws:s3:::test-goodtables/*"
            ]
        }
    ]
}
```

Super-annoyingly, you can't configure the policy to return **only** the buckets that it enables access on, it's either all buckets in your account (with `s3:GetBucketLocation` and `s3:ListAllMyBuckets`) or none. So users will need to enter the name of the bucket (or select the relevant one from a list that includes buckets where the application has no access, which is terrible UX).

Once this has been configured on AWS and the settings entered on GTIO (access key and secret key for the limited role, bucket name(s)) we can perform a call to check that the permissions are correctly set up (calling the relevant boto functions to list the objects in a bucket and get the contents of one of them).


TODO this is still unclear, need to clean up and decide best approach:

Notifications, automatically create, need to add `s3:GetBucketNotification`, `s3:PutBucketNotification` to the policy.
NOTE: Notifications in S3 are *per object* (ie if you upload 10 csv, we'll get 10 notifications)
Where to send them? SNS or a lambda function?
Ideally we reuse the same lambda function, will it have perms to read all buckets contents?
Lambda computes a temp URL with `generate_presigned_url()` and sends this to gt.io, with any additional metadata needed, (including a `goodtables.yml` file present in the bucket?)

There is a hook in GT.io that listens to these requests and fires the validation

**Comment by pwalsh** [comment]
@amercader 

many services connect with AWS services, and just ask the user to provide keys - oauth is orthogonal, so I'm not 100% sure what you are trying to do with oauth. I'd expect that our S3 integration is "configure your bucket, private us access crews for some user you set up". 

Also providing single bucket access is, again, a matter of the right policy, but that the user's concern for an initial version, not ours. In any event, we have several S3 policies at OKI that are bucket-specific we can copy from.

Notifications are per object on S3, but seeing as we have a `goodtables.yml` config file, we can listen for that object, and then have a polling system as a lambda function to check that all its dependencies are present.

**Comment by amercader** [comment]
@pwalsh yes, we are saying the same thing, only it took it me a while to learn how things work on AWS. 

I think we have a responsibility to guide users so they don't provide keys that allow too much, but yes, this is a matter of UI and UX that can be tackled later

**Comment by amercader** [comment]
OK, I got all the pieces of the puzzle working:

* Update a file to S3
* Trigger a Lambda function
* Parse the event data, get temporary signed URL , optionally a goodtables.yml file and send them to a GT.io hook
* Hook receives the payload and creates a validation job pointing to the S3 URLs

This looks deceptively simple, mostly because we are talking about a cross-account process and there's quite a bit of setup to be done.

* Account A is the OKI (or a dedicated GTIO) one. We control this one so we can get all that we will need (access key, secret key, account id)
* Account B is the GTIO user one, with access to the S3 bucket(s). We will need the user to provide access key, secret key and bucket name(s). (We can guide users to create an account limited to the buckets needed)

Once we have all this we need to:

1. On Account A, give permissions to the Bucket B1 to invoke our Lambda function A1:

    ```python
    client_A.add_permission(
        FunctionName={LAMBDA_ARN},
        StatementId={SOME_UNIQUE_STATEMENT_ID},
        Action='lambda:InvokeFunction',
        Principal='s3.amazonaws.com',
        SourceArn='arn:aws:s3:::{BUCKET_NAME}')
    ```

2. On Account B, add the bucket notification pointing to our lambda function:

    ```python
   client_B.put_bucket_notification_configuration(
       Bucket={BUCKET_NAME},
       NotificationConfiguration={
           'LambdaFunctionConfigurations': [
               {
                   'Id': {SOME_UNIQUE_NOTIFICATION_ID},
                   'LambdaFunctionArn': {LAMBDA_ARN},
                   'Events': [
                       's3:ObjectCreated:*'
                   ]
               },
           ]
       }   
   )
    ```
    You can apply filters here to restrict the triggering of the notification to certain extensions. In theory we could restrict it to the ones supported by tabulator (plus `goodtables.yml`) but that would make difficult to update the value in the future so perhaps is worth having notifications triggered on all files and filter at the lambda function level. On the other hand this might mean a lot more execution time (ie $ eventually).

3. On Account B, add the following bucket policy:

    ```python
    bucket_policy = '''
    {
        "Version": "2012-10-17",
        "Id": {SOME_UNIQUE_POLICY_ID},
        "Statement": [
            {
                "Sid": {SOME_UNIQUE_STATEMENT_ID},
                "Effect": "Allow",
                "Principal": {
                    "AWS": {ACCOUNT_A_ID}
                },
                "Action": [
                    "s3:ListBucket",
                    "s3:GetBucketLocation",
                    "s3:GetBucketNotification"
                ],
                "Resource": "arn:aws:s3:::{BUCKET_NAME}"
            }
        ]
    }'''
    
    client_B.put_bucket_policy(Bucket={BUCKET_NAME}, Policy=bucket_policy)
    
    ```

   This is not strictly required for the notifications to work, but without it we can not list the existing triggers on the lambda function console (you get `Access Denied` otherwise) from Account A. This is important to monitor what buckets are invoking the function. We can probably restrict the `Principal` to something more specific than the whole account. Of course we won't blindly override the policy, we'll get any existing one and add our statement to it if necessary.

TODO: Consider lambda function versions on 1 and 2.

In terms of implementation we need:

1. At the GTIO app level:
    * [ ] Model to safely store the user keys and bucket names (What @roll proposed on https://github.com/frictionlessdata/goodtables.io/issues/96#issuecomment-272135484)
    * [ ] Simple UI to provide these (`/s3/settings`)
    * [ ] Configure endpoint to perform the 3 steps above using helper functions that leverage boto3
    * [ ] Hook endpoint that receives payloads from the lambda function and:
        * Validates a signature to make sure it's coming from the lambda function
        * Validates the payload
        * Parses goodtables.yml
        * Creates a validation job. 

2. A Lambda function that receives notifications from S3 buckets, gets a signed URL for the key and sends it to the GTIO hook (see comment about filtering above, also needs to sign the request somehow). If we want to use external libraries (runtime is Python 2.7) we can create a [Deployment Package](http://docs.aws.amazon.com/lambda/latest/dg/lambda-python-how-to-create-deployment-package.html).

**Comment by amercader** [comment]
Closing this in favour of individual issues labelled `s3`
