### ISSUE TITLE
goodtables.yml [2.5d]

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#6]
# Description

We'll need a `goodtables.yml` parser, which takes the file or a link to a remotely accessible one and returns a list of configuration options, including:

* Fully resolved paths or links to tabular files.
* Schemas to be used
* (optional for MVP) Other configuration options: eg checks to run, etc

Example configuration:

```
# .goodtables.yml

# everything that is tabular
files: '*'

# everything that is csv
files: '*.csv'

# everything that is tabular in a certain directory
files: 'data/*'

# specifics
files:
  -
    path: 'budget.csv'
    schema: 'schemas/budget.json'
  -
    path: 'budget2.csv'
    schema: 'schemas/budget.json'
  -
    path: 'companies.csv'
```

Once the API has dropped a payload to S3 or some filesystem, then in order to run a job that is basically a good tables batch run, we need to have parsed the spec file and generated a list of paths to files for use in that batch.

# Tasks

- [ ] Define the parameters needed for the validation job to run (ie the outputs of parsing `.goodtables.yml`)
- [ ] Write a YML spec for how to model these parameters
- [ ] Implement the parser

# Estimate

3

**Comment by amercader** [comment]
@pwalsh @roll Some questions:

* In general, do we want to physically download the files on whatever platform the validation jobs are running or stream them directly from where they are hosted (if publicly available of course)

* Do we need support for DataPackages? ie

    ```
# .goodtables.yml

files: 'datapackage.json'
```
    Most of the examples on FD don't have a separate schema as in the examples above, but it is embedded in the `datapacakage.json` file, so it seems like a good idea to support it (We could even have goodtables.yml optional for repos/sources that provide a datapackage.json, as it has all the info we need, apart from more specific validation options)

**Comment by pwalsh** [comment]
I think it is safer and possibly more efficient to copy the files into our storage (but only the files that match the goodtables.yml spec not all files in a remote directory). Then it makes it simpler to re-run jobs, either in the case of a failed job, or the possibility of re-running history, like on a CI server.

it might mean that we combine this with the space that we store reports

- `/{userid}/{runid}/sources/*`
- `/{userid}/{runid}/report.json`

For supporting datapackages directly, it is useful but a great "after MVP feature" as it is not needed for piloting.
