### ISSUE TITLE
User interface to manage integrations

### ISSUE THREAD

**Issue by pwalsh** [frictionlessdata/goodtables.io#64]
# Description

As a user, I want to be able to configure my plugins with the supported GoodTables.io backends, so that I can use GoodTables.io to validate my data sources.

- Configure/activate plugin
- Edit existing plugin
- Remove plugin

As I start we can have:

* `/` for logged in users shows  a dashboard with the X more recent jobs per plugin type. Each section has a title that links to the plugin page and Settings link
* `/<plugin_name>`: all jobs (paginated) for this plugin
* `/<plugin_name>/settings`: plugin-specific configuration: eg for Github list of repos enabled, only validate repos, etc. + Authorize / Unauthorize.

# Tasks

- [ ] Link from the fronted page / dashboard to different plugins page (Github)
- [ ] `/github` page showing only github based jobs
- [ ] `/github/settings` page showing repos and authorization status

**Comment by amercader** [comment]
See #101 for details
