### ISSUE TITLE
Backend support for long-running tasks not related to validation jobs

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#89]
## Overview

Some processes that are not validation jobs take too long for a normal web request (For example Github repos syncing).

We just need a simple way of running these as celery tasks and an endpoint to check it status regularly from the frontend.

To keep the naming consistent I would call these **Internal Jobs**, as opposed to **Validation jobs** (the ones we've been dealing with up until now). I prefer to stick to jobs because they might involve multiple celery tasks in the future).

## Tasks

- [x] Set up a dedicated Celery queue for internal processes ([docs](http://docs.celeryproject.org/en/latest/userguide/routing.html)). This might affect #119 as we will need a separate worker for it
- [x] Create a new table and model to hold internal jobs metadata. @roll These seem so close to the current jobs (id, status, created, result, error, etc) that I'm tempted to use the same base `Job` model and some SQLAlchemy inheritance (as described in https://github.com/frictionlessdata/goodtables.io/issues/104) to reuse as much as we can
- [ ] Common endpoint for checking status of internal jobs (only accessible to admins / site users)
- [ ] Helper for purging ongoing tasks from the queue based on a specific criteria (eg Github user name)

**Comment by pwalsh** [comment]
There are many solutions of course, but polling from a modern frontend framework every X seconds, and then updating the view when the data is available, with a page reload, is a trivial pattern and scales very well - well beyond our needs ([a ~ famous example of simple ajax polling on a very high traffic app - see the Ajax polling section](http://blog.trello.com/the-trello-tech-stack)).

**Comment by roll** [comment]
@pwalsh 
Also there is a problem because flask is blocking we create celery task for it. So there also a need to store celery task_id on server side.

**Comment by pwalsh** [comment]
@roll sure, sounds fine:

- take sync request (for example)
- put on highest priority celery queue and return a job id
- client polls an endpoint that says if job is pending or done.
- if job done, client updates view.
- if job pending for longer than X period, client tells user there is a connection issue - try to resend in a few mins, and stops polling.
- on next client resync, purge pending ids for that user if they are still in the queue for some reason, and push in the new job

Definitely need to store this info in a db table.

**Comment by roll** [comment]
> Definitely need to store this info in a db table.
So that's my proposal too.

PS.
Some our vocabulary decisions to talk the same language:
task - celery task
job - goodtables job (could be one celery task or composition of them)

**Comment by pwalsh** [comment]
updated to use task.

**Comment by pwalsh** [comment]
@amercader for your consideration, esp. in reference to comments in #91

**Comment by amercader** [comment]
@pwalsh @roll not sure if you get notified of description changes, so I updated this one (backend) and #91 (github repos). Let me know if they make sense.
