### ISSUE TITLE
Move current Jinja2 templates to Vue

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables.io#92]
*edited*: text by @pwalsh

# Description

We want a fundamental split between the client and the server - I won't go into the technical and maintenance reasons for why here, and I'll just assume that everyone is on board.

The current UI is the bare minimum to make things work, but we do not want to walk any further down the path of server-side rendering or consuming data via specific view/controllers, rather than API end points.

This issue captures the *first iteration* towards the "real UI/X" for goodtables.io -  the goal is the port *existing* functionality to a frontend framework. While the issue is about frontend implementation, it will almost certainly require some changes to the server - whiting some data and logic from controllers to API end points.This aspect should not be laboured over - do what needs to be done to get the frontend right, and we can clean up APIs after we see the pattern emerge from this iteration.

# Tasks

- [x] Choose framework
- [x] Bootstrap the framework - runners for building source, etc. Use ES6, please
- [x] Setup base templates to remove basic templating from jinja to new framework
  - [x] Choice of 100% static, or render out header/footer in jinja and let the framework take over the whole content area. Second option often seems ok at first, but in my experience can lead to issues, when design, fro example, requires dynamic elements in a header. This is less of an issue in node where one can often just shift logic and templates from backend to frontend, but in python need to think about your choice.
- [x] Implement all current (mock) UI. Don't try to reinvent anything in terms of UI elements until we get https://github.com/frictionlessdata/goodtables.io/issues/112 as it will be wasted effort.
  - [x] Probably requires some shifting of logic and data to API endpoints. Should be quite trivial with our flask setup.
- [x] ~~*Do* change things that are interactive, but not about UI exactly - I specifically mean that crazy reload loop we have now for syncing repos :). That is the type of thing to fix on this issue/iteration.~~ -> MOVED to #137, #138
- [ ] Tests, of course.

Pages

- [x] Dashboard
- [x] Source list(s)
- [x] Job report (#121)
- [x] Github Settings

**Comment by pwalsh** [comment]
@amercader @roll I'll suggest we close/change this issue to implementing usage of a frontend framework, and a client side app that talks to our server. Pending on the MVP scope doc I am working on.

**Comment by pwalsh** [comment]
@amercader assigned for review of scope, comments, and high-level estimate.

**Comment by roll** [comment]
Ok, if we're going that way (strict API and UI separation) it will be easier to work in separated repositories (API and UI) because having python and javascript in one repository is possible (like building on travis with some hacks) but kinda messy. 

But splitting repos could cause extra work with API mocking (see OpenTrials) etc.

**Comment by pwalsh** [comment]
I wouldn't split the repositories right now, it is harder in the short term. Best to keep it together until we finish the beta milestone. can extract out later. 

Especially as this issue captures a transition from the current setup to one running on the API, it would not be possible to seperate and work iteratively (transition where some calls are via API, some are via the existing controllers, for example).

It is not really "messy" in travis: you use the setup you have now, but also install nvm and use a latest node version via it, to run your frontend build.

**Comment by amercader** [comment]
@roll Do you want individual issues for this (see list of pages I added to the description)? Maybe it makes it easier to estimate and track. Otherwise can I assume that 5 days includes everything? We can definitely make it more accurate but you have a better idea of the time to be spent.

Is this done?
> Bootstrap the framework - runners for building source, etc. Use ES6, please

**Comment by roll** [comment]
@amercader it's ok not split. Yes I've added estimation for the whole thing. I'll be updating task list when we will start merge PRs for it

**Comment by roll** [comment]
@amercader 
So except `index.html` we don't have any other jinja2 templates in the codebase. For this issue we miss only use unit tests (I'm going to finish).

Also I've extracted 2 individual issues for interactions:
- #137 
- #138 

We could check for other interactions to convert later but I suppose #92 + #137 + #138 will cover this issue initial requirements.
